# Generated by Django 3.0.8 on 2020-08-02 08:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 8, 6, 34, 99868, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='question',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 8, 6, 34, 100441, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 8, 6, 34, 99281, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='quiz',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choices', to='app.Question'),
        ),
    ]
