# Generated by Django 3.0.8 on 2020-08-02 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200802_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 8, 13, 45, 448060, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 8, 13, 45, 446869, tzinfo=utc)),
        ),
    ]
