# Generated by Django 3.0.8 on 2020-08-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200802_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
