# Generated by Django 3.1 on 2020-08-09 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20200809_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztestresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_test_results', related_query_name='quiz_test_result', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuizTestResultAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_answers', related_query_name='result_answer', to='app.questionchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_answers', related_query_name='result_answer', to='app.question')),
                ('quiz_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_answers', related_query_name='result_answer', to='app.quiztestresult')),
            ],
        ),
    ]
